---
title: 'Part 3: Recreate'
output:
  pdf_document: default
  html_document: default
date: "2025-03-14"
---

```{r}
library(ggplot2)
library(dplyr)
```

```{r}
mobiles_dataset<- "C:/Users/asus/Desktop/Homework 3/mobiles_dataset.csv"
```

```{r}
data<- read.csv(mobiles_dataset)
```

```{r}
ggplot(data, aes(x = Company.Name, y = Launched.Price.USA.USD, fill = Company.Name)) +
  theme_minimal() +
  geom_boxplot(alpha = 0.6) +                                                                         
  geom_jitter(width = 0.2, size = 1, color = "black", alpha = 0.7) +   
  labs(
    title = "Price Distribution by Company in USA",
    subtitle = "A boxplot showing how the price varies by company, with individual data points overlaid",
    x = "Company",
    y = "Price in USD"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
```{r}
ggplot(data, aes(x = Battery.Capacity.mAh, y = Launched.Price.USA.USD, color = Company.Name)) +
  geom_point(alpha = 0.7, size = 3) +
  theme_minimal() +
  labs(
    title = "Battery Capacity vs. Price in USA",
    subtitle = "The relationship between battery capacity, price, and screen size across different smartphone brands",
    x = "Battery Capacity (mAh)",
    y = "Price"
  )
```


```{r}

top_brands <- data %>%
  count(Company.Name, sort = TRUE) %>%
  top_n(5, n) %>%
  pull(Company.Name )

data_top5 <- data %>% filter(Company.Name  %in% top_brands)

data_top5$Company.Name <- as.factor(data_top5$Company.Name)

ggplot(data_top5, aes(x = Battery.Capacity.mAh, y = Launched.Price.USA.USD, shape = Company.Name,
                      color = Battery.Capacity.mAh)) + 
  geom_point(size = 3, alpha = 0.8) +
  scale_shape_manual(values = c("Apple" = 16, "Honor" = 17, "Samsung" = 15, "Vivo" = 16, "Oppo" = 18)) +
  scale_color_gradient(low = "#607B8B", high = "#87CEFA", guide = "none") +  
  theme_minimal() +
  labs(
    title = "Battery Capacity vs. Price for Top 5 Brands",
    subtitle = "Gradient Blue Based on Battery Capacity (USA)",
    x = "Battery Capacity (mAh)",
    y = "Price (USD)",
    color = "Battery Capacity",
    shape = "Brand"
  )
```



